# Site settings
title: "Farshad N. Heravi"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Farshad N. Heravi"
resume_title:                   "A Robotics enthusiast"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "Farshad.NozadHeravi@iit.it"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+39) 379 210 8830"
resume_contact_address:         "Genoa, Italy"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I have a keen interest in working with robots and having them perform various tasks autonomously. This goal requires me to work on several aspects such as Robot Dynamics, Control, Perception, and Learning. I have been worked in different projects for each of these requirements. Explore the webpage to get familiar with the project and the tools I have used.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/farshad-heravi"
  resume_twitter_url:           ""
  resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://linkedin.com/in/fheravi"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://farshad-heravi.github.io"
  resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
